<?php

namespace Container2k3fsYU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4N2tuNNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4N2tuNN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4N2tuNN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cart' => ['privates', '.errored..service_locator.4N2tuNN.App\\Classe\\Cart', NULL, 'Cannot autowire service ".service_locator.4N2tuNN": it references class "App\\Classe\\Cart" but no such service exists.'],
        ], [
            'cart' => 'App\\Classe\\Cart',
        ]);
    }
}
