<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZL2yZjq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZL2yZjq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZL2yZjq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZL2yZjq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZL2yZjq\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZL2yZjq',
    'container.build_id' => '698f3b5c',
    'container.build_time' => 1611746891,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZL2yZjq');
