<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD8F7vKp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD8F7vKp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD8F7vKp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD8F7vKp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD8F7vKp\App_KernelDevDebugContainer([
    'container.build_hash' => 'D8F7vKp',
    'container.build_id' => '830aa39a',
    'container.build_time' => 1611617126,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD8F7vKp');
